### ISSUE TITLE
Zu unbekannt

### ISSUE THREAD

**Issue by dreua** [rwolke/thw-theorie#1]
Die Webapp ist super zum lernen genau das was ich gesucht habe!

Das einzige Problem ist, dass sie recht schwer zu finden war - vielleicht könnte man hieran noch arbeiten, ein paar Ideen:

- Übers THW über das Angebot informieren (mache ich in meinem OV, aber vielleicht gibt es auch einen bundeweiten Ausbilder-Verteiler über den man das mal verschicken könnte)
- Eigene Domain 
- evtl. Einbettung in eine Android-App für den Playstore (dort habe ich zuerst gesucht und nichts gefunden)

Falls gewünscht helfe ich gerne mit, fände es irgendwie schade, wenn gute Software nicht genutzt wird weil keiner davon weiß.

**Comment by rwolke** [comment]
Moin David,

freut mich, dass du die App gut findest. 

Zu den Punkten:

1. Ich habe schon öfters Mails an kompetenzentwicklung .. thw.de geschickt, leider kaum Antwort bekommen. Selbst Hinweise auf Fehler in Ausbildungsunterlagen mit genauen Anweisungen zur Korrektur brauchen manchmal mehr als 6 Monate und Erinnerungen. Wenn es da einen anderen besseren Weg gibt, bin ich dafür offen (und du darfst das gerne promoten), allerdings mag ich da selber keine Energie mehr reinstecken, mir reicht es wenn ich es ein paar Leuten persönlich empfehlen kann...

2. Gerne auch das. Die Domain kann dann ja recht einfach mit den Github-Pages verknüpft werden. Allerdings will ich auch da selber keine Mühe oder Geld investieren (oder wohlmöglich sogar Ärger bekommen, wenn ich eine Domain mit thw im Namen registriere, siehe THWiki)

3. Von dem ganzen App-Wahnsinn halte ich nicht viel. Jeder kann ein Lesezeichen zu dieser Webseite über den Mobil-Browser zu seinem Start-Bildschirm hinzufügen und schon hat man das gleiche Ergebnis... Aber auch da: Wenn jemand anderes es machen möchte, darf es gerne weiterentwickelt werden.

Aktuell bin ich auch gar nicht mehr im THW aktiv, deshalb weiß ich noch nicht was langfristig aus der App werden wird... Minimal würde ich die App offline nehmen, sobald sie nicht mehr gültig ist (neuer Fragenkatalog). Und maximal werde ich aber nur so viel Energie reinstecken um neue Fragenkataloge einzupflegen und die Skripte so zu pflegen, das die Anwendung lauffähig bleibt. Für mich war das Projekt nur ein Einstig um mich für eine andere Anwendung mit JQueryMobile vertraut zu machen...

Wenn du mehr daraus machen möchtest, kannst du aber gerne mitwirken, gerne schalte ich dir dann Zugriffe im Repository frei und unterstütze wenn es meine Zeit erlaubt & mir danach ist... 

Alles weitere gerne per Mail (in der App genannt) und ja, die Mails bekomme ich noch...

Gruß
Robert
