### ISSUE TITLE
Fragen der Version 3.3

### ISSUE THREAD

**Issue by psz-dev** [rwolke/thw-theorie#4]
Hey,

gibt es zufällig jemanden der die Fragen der Version 3.3 (Stand März 2020) hat, der wo gäbe es Möglichkeiten wo ich die Fragen als JSON her bekomme (kann man die offizielle PDF irgendwie umwandeln) ?

**Comment by psz-dev** [comment]
Ich hab's jetzt mit einem Python Skript und einem PDF Konverter gelöst ;)

**Comment by dreua** [comment]
Lad das Ergebnis oder den Weg dorthin evtl einfach hier hoch oder lass einen Link da, für den Fall, dass es mal jemand sucht 😉

**Comment by psz-dev** [comment]
Hier schonmal mein Vorgehen:

1. Umwandlung der PDF mit dem Lösungen mit einem PDF to Excel Konverter
2. entfernen von Logo, Tabellen, Header, usw.
3. Export als CSV (Trennzeichen `;`) 
   **WICHTIG:** Aufpassen, dass das Trennzeichen in keiner Frage vorkommt, ggf. entfernen!
4. Python Script:
```
import json
c_all = []
f_o = open("dateiAusExcel.csv").read()
f = f_o.split(";")
i = 0
while True:
    if(i >= len(f)):
        break
    if f[i] != "":
        q = f[i]
        q_c = int(f[i].split(",")[0])
        q_n = int(f[i].split(",")[1])
        correct = []
        if f[i+4] == "X":
            correct.append(1)
        if f[i+10] == "X":
            correct.append(2)
        if f[i+16] == "X":
            correct.append(3)
        c = {"answers": {"1": f[i+2], "2": f[i+8], "3": f[i+14]}, "category": q_c, "correct": correct, "number": q_n, "question": f[i+1] }
        c_all.append(c)
    i+=18
f = open("export.json", "a")
f.write(json.dumps(c_all))
f.close()
```

5. Manuelles Hinzfügen der restlichen Felder (Version, category)

**Comment by rwolke** [comment]
Hallo zusammen,

ich hab die [_helper/parse.php](https://github.com/rwolke/thw-theorie/blob/master/_helper/parse.php) an die aktuelle PDF-Version 3.3 aus ILIAS angepasst. Damit klappt jetzt die Umwandlung wieder und ihr könntet euch die JSON selbst generieren.
Ebenso habe ich die index.html angepasst, sodass sie die entstehende questions_2020v33.json verwendet werden kann. Die Datei lasse ich euch sonst gerne über Hermine zukommen, die Veröffentlichung wurde mir ja von der THW-Leitung untersagt! 

Die Auseinandersetzung mit der THW-Leitung war sehr zäh... Könnt ihr gerne selber unter https://fragdenstaat.de/a/182389 nachlesen. Da hatte ich keine Meinung mehr... Wenn man in EA und zuletzt U3 hier so viele Steine in den Weg wirft, dann lasse ich es halt bleiben... Sehr traurig... 

Gruß
Robert

**Comment by dreua** [comment]
> Sehr traurig...

Schade, ich hab mich damals zum Glück noch super mit deiner App auf die GA-Prüfung vorbereiten können, danke dafür!
